version: 2
jobs:
  beam:
    working_directory: ~/fialyzer
    docker:
      - image: erlang:21.1.2-alpine
    steps:
      - checkout
      - run:
          name: Install System Deps
          command: apk add --no-cache ca-certificates make bash
      - run:
          name: Compile erl files
          command: make beam
      - persist_to_workspace:
          root: .
          paths:
            # CircleCI does not support globstar pattern (`**/*.beam`).
            # So you must list concrete filepaths if you want to add BEAM files.
            - ./test/blackbox-test/test-cases/*.beam
  build:
    working_directory: ~/fialyzer
    docker:
      - image: ocaml/opam2:alpine-3.8-ocaml-4.07
    steps:
      - run:
          name: Install System Deps
          # NOTE: You must install git and openssh before checkout, otherwise submodule will not be updated.
          command: sudo apk add --no-cache m4 make zlib-dev gmp-dev perl git openssh bash
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install
          command: eval $(opam config env) && opam repo add remote-default https://opam.ocaml.org && opam pin add -y fialyzer .
      - run:
          name: Test
          # NOTE: Don't run `make test` because `make test` requires Erlang/OTP.
          command: eval $(opam config env) && make unit-test && make blackbox-test
      - run:
          name: OCamldoc
          command: eval $(opam config env) && opam install odoc && make doc
      - persist_to_workspace:
          root: _build/default
          paths: _doc/_html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: _build/default
      - run:
          name: Install gh-pages and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "c2:9b:11:57:ef:01:b7:0e:21:50:48:d0:35:72:e5:86"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --message "[skip ci] doc upload" --dist _build/default/_doc/_html --dest odoc
workflows:
  version: 2
  all:
    jobs:
      - beam
      - build:
          requires:
            - beam
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
